openapi: 3.0.0
info:
  title: Sample API Test clients
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://127.0.0.1:8000/api
    description: Optional server description, e.g. Main (production) server
  # - url: http://staging-api.example.com
  #   description: Optional server description, e.g. Internal staging server for testing
tags: 
  - name: Authorization Email
paths:
  /auth/register:
    post:
      summary: "Register by email"
      tags: 
        -  Authorization Email
      requestBody: 
        $ref: ./components/requestBodies/authorization/email/Register.yml
      responses: 
        200: 
          description: "awdadawd"
        422:
          $ref: ./components/responses/4xx/422/EmailAlreadyBeenTaken.yml

  /auth/login:
    post:
      summary: "Login by email"
      tags: 
        -  Authorization Email
      requestBody: 
        $ref: ./components/requestBodies/authorization/email/Login.yml
      responses: 
        200: 
          $ref: ./components/responses/authorization/LoginResponse.yml
        403: 
          $ref: ./components/responses/4xx/InvalidCredentials.yml

  /countries:
    get:
      summary: Get public countries
      responses:
        200:    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string